import{a as m,S as w}from"./assets/vendor-c27ca954.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const L="43229178-92086ef52b57e39ce4e68da2d",b=15;async function d(e,t=1){const s=`https://pixabay.com/api/?key=${L}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${b}`;try{const n=await m.get(s);if(n.status!==200)throw new Error("Network response was not ok");return n.data.hits}catch(n){throw console.error("Error fetching images:",n),n}}function v(e){return`
    <div class="card">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <div class="stats">
        <span>Likes: ${e.likes}</span>
        <span>Views: ${e.views}</span>
        <span>Comments: ${e.comments}</span>
        <span>Downloads: ${e.downloads}</span>
      </div>
    </div>
  `}function a(e){iziToast.error({title:"Error",message:e})}const P=document.querySelector(".search-form"),l=document.querySelector(".gallery"),f=document.querySelector(".loader"),u=document.querySelector(".load-more-btn"),$=new w(".gallery a",{});let i=1,y="";function h(){f.style.display="block"}function p(){f.style.display="none"}function E(){u.style.display="block"}function S(){u.style.display="none"}P.addEventListener("submit",q);u.addEventListener("click",M);async function q(e){e.preventDefault();const t=e.target.search.value.trim();if(!t){a("Please enter a search query");return}i=1,y=t;try{h(),l.innerHTML="";const s=await d(t);s.length===0?a("Sorry, there are no images matching your search query. Please try again!"):(g(s),E())}catch{a("An error occurred while fetching images. Please try again later.")}finally{p()}}async function M(){i++;try{h();const e=await d(y,i);e.length===0?(S(),a("We're sorry, but you've reached the end of search results.")):(g(e),A())}catch{a("An error occurred while fetching more images. Please try again later.")}finally{p()}}function g(e){const t=e.map(v).join("");l.insertAdjacentHTML("beforeend",t),$.refresh()}function A(){const e=l.getBoundingClientRect().height*2;window.scrollBy({top:e,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
